### ISSUE TITLE
プリセットルールの精査

### ISSUE THREAD

**Issue by herablog** [openameba/textlint-rule-preset-ameba#1]
[仮で作ったプリセットルール](https://github.com/openameba/textlint-rule-preset-ameba/blob/64c913bd53755cb5491390a109f7aec6cf0b3bb2/lib/textlint-rule-preset-ameba.js)を精査し、実用的なものにします。

その際には、「必ず直したいルール」「できれば直したいルール」の2つに分類します。

**Comment by herablog** [comment]
Amebaのガイドライン「漢字は5個以上連続させない」に合わせて、`textlint-rule-max-kanji-continuous-len`を`4`に指定しよう。

**Comment by herablog** [comment]
以下のルールを追加予定です。

## 必ず直したいルール (Error)
- textlint-rule-ja-space-between-half-and-full-width
- textlint-rule-ja-no-space-between-full-width
- textlint-rule-ja-nakaguro-or-halfwidth-space-between-katakana
- textlint-rule-ja-no-space-around-parentheses
- textlint-rule-ja-no-successive-word

## できれば直したいルール (Warning)
- textlint-rule-no-double-negative-ja

@tokimari textlint-rule-no-double-negative-ja はどちらに入れるか意見を聞きたいです。

**Comment by tokimari** [comment]
> textlint-rule-no-double-negative-ja

「やさしい日本語」の基準のうちの１つとして、二重否定を使わない、というものが挙げられています。
http://miajapan.sakura.ne.jp/nihongo/201911gijiroku2.pdf （原典のサイトは閉鎖してしまったのでpdfで・・）
「やさしい日本語」は外国の方を想定して、オリンピック向けサイトでも１つの指標として挙げられています。
[「やさしい日本語」について | 2020年オリンピック・パラリンピック大会に向けた　多言語対応協議会ポータルサイト](https://www.2020games.metro.tokyo.lg.jp/multilingual/references/easyjpn.html#:~:text=%E3%80%8C%E3%82%84%E3%81%95%E3%81%97%E3%81%84%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%80%8D%E3%81%A8%E3%81%AF%E3%80%81%E6%99%AE%E9%80%9A%E3%81%AE%E6%97%A5%E6%9C%AC%E8%AA%9E,%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E4%BA%BA%E3%82%82%E3%81%84%E3%81%BE%E3%81%97%E3%81%9F%E3%80%82)

で、「やさしい日本語」のレベル感ですが、
> 旧日本語能力試験3級程度の日本語（小学校3年生の学校文法）で理解できる、吟味した簡潔な日本語「やさしい日本語」を研究、考案した。
> ここでは、小学校3年生とありますが、先の「日本語を勉強し始めて３か月以上６か月未満（学習時間400時間）」とほぼ同じくらいのレベルを想定しているものと思われます。
[「Plain English」と「やさしい日本語」 | Junnama Online](http://junnama.alfasado.net/online/2018/12/plain_english_and_easy_japanese.html)

とあります。二重否定の用法が小３レベル相当とすると、そこまで難しい用法ではなさそうに思いますが、WAICの達成方法集（[G153: テキストを読みやすくする | WCAG 2.0 達成方法集](https://waic.jp/docs/WCAG-TECHS/G153.html)）の中には挙げられていません。

やった方がいいけど必須ではないのでは？ということで、warning相当でいいかなと感じました:eyes:

**Comment by herablog** [comment]
実運用進んでるので、こちらはcloseします〜
